/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PasswordsRouteImport } from './routes/passwords'
import { Route as InjectsRouteImport } from './routes/injects'
import { Route as FilesRouteImport } from './routes/files'
import { Route as AllowedIpsRouteImport } from './routes/allowed-ips'
import { Route as IndexRouteImport } from './routes/index'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordsRoute = PasswordsRouteImport.update({
  id: '/passwords',
  path: '/passwords',
  getParentRoute: () => rootRouteImport,
} as any)
const InjectsRoute = InjectsRouteImport.update({
  id: '/injects',
  path: '/injects',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AllowedIpsRoute = AllowedIpsRouteImport.update({
  id: '/allowed-ips',
  path: '/allowed-ips',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allowed-ips': typeof AllowedIpsRoute
  '/files': typeof FilesRoute
  '/injects': typeof InjectsRoute
  '/passwords': typeof PasswordsRoute
  '/services': typeof ServicesRoute
  '/websites': typeof WebsitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allowed-ips': typeof AllowedIpsRoute
  '/files': typeof FilesRoute
  '/injects': typeof InjectsRoute
  '/passwords': typeof PasswordsRoute
  '/services': typeof ServicesRoute
  '/websites': typeof WebsitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allowed-ips': typeof AllowedIpsRoute
  '/files': typeof FilesRoute
  '/injects': typeof InjectsRoute
  '/passwords': typeof PasswordsRoute
  '/services': typeof ServicesRoute
  '/websites': typeof WebsitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allowed-ips'
    | '/files'
    | '/injects'
    | '/passwords'
    | '/services'
    | '/websites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allowed-ips'
    | '/files'
    | '/injects'
    | '/passwords'
    | '/services'
    | '/websites'
  id:
    | '__root__'
    | '/'
    | '/allowed-ips'
    | '/files'
    | '/injects'
    | '/passwords'
    | '/services'
    | '/websites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllowedIpsRoute: typeof AllowedIpsRoute
  FilesRoute: typeof FilesRoute
  InjectsRoute: typeof InjectsRoute
  PasswordsRoute: typeof PasswordsRoute
  ServicesRoute: typeof ServicesRoute
  WebsitesRoute: typeof WebsitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwords': {
      id: '/passwords'
      path: '/passwords'
      fullPath: '/passwords'
      preLoaderRoute: typeof PasswordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/injects': {
      id: '/injects'
      path: '/injects'
      fullPath: '/injects'
      preLoaderRoute: typeof InjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allowed-ips': {
      id: '/allowed-ips'
      path: '/allowed-ips'
      fullPath: '/allowed-ips'
      preLoaderRoute: typeof AllowedIpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllowedIpsRoute: AllowedIpsRoute,
  FilesRoute: FilesRoute,
  InjectsRoute: InjectsRoute,
  PasswordsRoute: PasswordsRoute,
  ServicesRoute: ServicesRoute,
  WebsitesRoute: WebsitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
