// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: northstar.proto

package northstarconnect

import (
	proto "bonfire/northstar/proto"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NorthstarName is the fully-qualified name of the Northstar service.
	NorthstarName = "northstar.Northstar"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NorthstarLoginProcedure is the fully-qualified name of the Northstar's Login RPC.
	NorthstarLoginProcedure = "/northstar.Northstar/Login"
	// NorthstarListHostsProcedure is the fully-qualified name of the Northstar's ListHosts RPC.
	NorthstarListHostsProcedure = "/northstar.Northstar/ListHosts"
	// NorthstarAddHostProcedure is the fully-qualified name of the Northstar's AddHost RPC.
	NorthstarAddHostProcedure = "/northstar.Northstar/AddHost"
	// NorthstarUpdateHostProcedure is the fully-qualified name of the Northstar's UpdateHost RPC.
	NorthstarUpdateHostProcedure = "/northstar.Northstar/UpdateHost"
	// NorthstarDeleteHostProcedure is the fully-qualified name of the Northstar's DeleteHost RPC.
	NorthstarDeleteHostProcedure = "/northstar.Northstar/DeleteHost"
	// NorthstarListServicesProcedure is the fully-qualified name of the Northstar's ListServices RPC.
	NorthstarListServicesProcedure = "/northstar.Northstar/ListServices"
	// NorthstarAddServiceProcedure is the fully-qualified name of the Northstar's AddService RPC.
	NorthstarAddServiceProcedure = "/northstar.Northstar/AddService"
	// NorthstarUpdateServiceProcedure is the fully-qualified name of the Northstar's UpdateService RPC.
	NorthstarUpdateServiceProcedure = "/northstar.Northstar/UpdateService"
	// NorthstarDeleteServiceProcedure is the fully-qualified name of the Northstar's DeleteService RPC.
	NorthstarDeleteServiceProcedure = "/northstar.Northstar/DeleteService"
	// NorthstarGetCredentialsProcedure is the fully-qualified name of the Northstar's GetCredentials
	// RPC.
	NorthstarGetCredentialsProcedure = "/northstar.Northstar/GetCredentials"
	// NorthstarListInjectsProcedure is the fully-qualified name of the Northstar's ListInjects RPC.
	NorthstarListInjectsProcedure = "/northstar.Northstar/ListInjects"
	// NorthstarAddInjectProcedure is the fully-qualified name of the Northstar's AddInject RPC.
	NorthstarAddInjectProcedure = "/northstar.Northstar/AddInject"
	// NorthstarUpdateInjectProcedure is the fully-qualified name of the Northstar's UpdateInject RPC.
	NorthstarUpdateInjectProcedure = "/northstar.Northstar/UpdateInject"
	// NorthstarDeleteInjectProcedure is the fully-qualified name of the Northstar's DeleteInject RPC.
	NorthstarDeleteInjectProcedure = "/northstar.Northstar/DeleteInject"
	// NorthstarListWebsitesProcedure is the fully-qualified name of the Northstar's ListWebsites RPC.
	NorthstarListWebsitesProcedure = "/northstar.Northstar/ListWebsites"
	// NorthstarAddWebsiteProcedure is the fully-qualified name of the Northstar's AddWebsite RPC.
	NorthstarAddWebsiteProcedure = "/northstar.Northstar/AddWebsite"
	// NorthstarUpdateWebsiteProcedure is the fully-qualified name of the Northstar's UpdateWebsite RPC.
	NorthstarUpdateWebsiteProcedure = "/northstar.Northstar/UpdateWebsite"
	// NorthstarDeleteWebsiteProcedure is the fully-qualified name of the Northstar's DeleteWebsite RPC.
	NorthstarDeleteWebsiteProcedure = "/northstar.Northstar/DeleteWebsite"
	// NorthstarListPasswordsProcedure is the fully-qualified name of the Northstar's ListPasswords RPC.
	NorthstarListPasswordsProcedure = "/northstar.Northstar/ListPasswords"
	// NorthstarSeedPasswordsProcedure is the fully-qualified name of the Northstar's SeedPasswords RPC.
	NorthstarSeedPasswordsProcedure = "/northstar.Northstar/SeedPasswords"
	// NorthstarUpdatePasswordCommentProcedure is the fully-qualified name of the Northstar's
	// UpdatePasswordComment RPC.
	NorthstarUpdatePasswordCommentProcedure = "/northstar.Northstar/UpdatePasswordComment"
	// NorthstarClearPasswordsProcedure is the fully-qualified name of the Northstar's ClearPasswords
	// RPC.
	NorthstarClearPasswordsProcedure = "/northstar.Northstar/ClearPasswords"
	// NorthstarListFilesProcedure is the fully-qualified name of the Northstar's ListFiles RPC.
	NorthstarListFilesProcedure = "/northstar.Northstar/ListFiles"
	// NorthstarUpdateFileProcedure is the fully-qualified name of the Northstar's UpdateFile RPC.
	NorthstarUpdateFileProcedure = "/northstar.Northstar/UpdateFile"
	// NorthstarDeleteFileProcedure is the fully-qualified name of the Northstar's DeleteFile RPC.
	NorthstarDeleteFileProcedure = "/northstar.Northstar/DeleteFile"
	// NorthstarAddHostPortProcedure is the fully-qualified name of the Northstar's AddHostPort RPC.
	NorthstarAddHostPortProcedure = "/northstar.Northstar/AddHostPort"
	// NorthstarDeleteHostPortProcedure is the fully-qualified name of the Northstar's DeleteHostPort
	// RPC.
	NorthstarDeleteHostPortProcedure = "/northstar.Northstar/DeleteHostPort"
	// NorthstarUpdateHostPortProcedure is the fully-qualified name of the Northstar's UpdateHostPort
	// RPC.
	NorthstarUpdateHostPortProcedure = "/northstar.Northstar/UpdateHostPort"
	// NorthstarAddServicePortProcedure is the fully-qualified name of the Northstar's AddServicePort
	// RPC.
	NorthstarAddServicePortProcedure = "/northstar.Northstar/AddServicePort"
	// NorthstarDeleteServicePortProcedure is the fully-qualified name of the Northstar's
	// DeleteServicePort RPC.
	NorthstarDeleteServicePortProcedure = "/northstar.Northstar/DeleteServicePort"
	// NorthstarImportHostsProcedure is the fully-qualified name of the Northstar's ImportHosts RPC.
	NorthstarImportHostsProcedure = "/northstar.Northstar/ImportHosts"
	// NorthstarClearHostsProcedure is the fully-qualified name of the Northstar's ClearHosts RPC.
	NorthstarClearHostsProcedure = "/northstar.Northstar/ClearHosts"
	// NorthstarAddServiceDependencyProcedure is the fully-qualified name of the Northstar's
	// AddServiceDependency RPC.
	NorthstarAddServiceDependencyProcedure = "/northstar.Northstar/AddServiceDependency"
	// NorthstarDeleteServiceDependencyProcedure is the fully-qualified name of the Northstar's
	// DeleteServiceDependency RPC.
	NorthstarDeleteServiceDependencyProcedure = "/northstar.Northstar/DeleteServiceDependency"
	// NorthstarListNetworksProcedure is the fully-qualified name of the Northstar's ListNetworks RPC.
	NorthstarListNetworksProcedure = "/northstar.Northstar/ListNetworks"
	// NorthstarAddNetworkProcedure is the fully-qualified name of the Northstar's AddNetwork RPC.
	NorthstarAddNetworkProcedure = "/northstar.Northstar/AddNetwork"
	// NorthstarUpdateNetworkProcedure is the fully-qualified name of the Northstar's UpdateNetwork RPC.
	NorthstarUpdateNetworkProcedure = "/northstar.Northstar/UpdateNetwork"
	// NorthstarDeleteNetworkProcedure is the fully-qualified name of the Northstar's DeleteNetwork RPC.
	NorthstarDeleteNetworkProcedure = "/northstar.Northstar/DeleteNetwork"
	// NorthstarListAllowedIPsProcedure is the fully-qualified name of the Northstar's ListAllowedIPs
	// RPC.
	NorthstarListAllowedIPsProcedure = "/northstar.Northstar/ListAllowedIPs"
	// NorthstarAddAllowedIPProcedure is the fully-qualified name of the Northstar's AddAllowedIP RPC.
	NorthstarAddAllowedIPProcedure = "/northstar.Northstar/AddAllowedIP"
	// NorthstarUpdateAllowedIPProcedure is the fully-qualified name of the Northstar's UpdateAllowedIP
	// RPC.
	NorthstarUpdateAllowedIPProcedure = "/northstar.Northstar/UpdateAllowedIP"
	// NorthstarDeleteAllowedIPProcedure is the fully-qualified name of the Northstar's DeleteAllowedIP
	// RPC.
	NorthstarDeleteAllowedIPProcedure = "/northstar.Northstar/DeleteAllowedIP"
)

// NorthstarClient is a client for the northstar.Northstar service.
type NorthstarClient interface {
	Login(context.Context, *connect.Request[proto.LoginRequest]) (*connect.Response[proto.LoginResponse], error)
	ListHosts(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.HostList], error)
	AddHost(context.Context, *connect.Request[proto.AddHostRequest]) (*connect.Response[proto.Host], error)
	UpdateHost(context.Context, *connect.Request[proto.UpdateHostRequest]) (*connect.Response[proto.Host], error)
	DeleteHost(context.Context, *connect.Request[proto.DeleteHostRequest]) (*connect.Response[proto.Empty], error)
	ListServices(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.ServiceList], error)
	AddService(context.Context, *connect.Request[proto.AddServiceRequest]) (*connect.Response[proto.Service], error)
	UpdateService(context.Context, *connect.Request[proto.UpdateServiceRequest]) (*connect.Response[proto.Service], error)
	DeleteService(context.Context, *connect.Request[proto.DeleteServiceRequest]) (*connect.Response[proto.Empty], error)
	GetCredentials(context.Context, *connect.Request[proto.CredentialRequest]) (*connect.Response[proto.CredentialList], error)
	ListInjects(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.InjectList], error)
	AddInject(context.Context, *connect.Request[proto.AddInjectRequest]) (*connect.Response[proto.Inject], error)
	UpdateInject(context.Context, *connect.Request[proto.UpdateInjectRequest]) (*connect.Response[proto.Inject], error)
	DeleteInject(context.Context, *connect.Request[proto.DeleteInjectRequest]) (*connect.Response[proto.Empty], error)
	ListWebsites(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.WebsiteList], error)
	AddWebsite(context.Context, *connect.Request[proto.AddWebsiteRequest]) (*connect.Response[proto.Website], error)
	UpdateWebsite(context.Context, *connect.Request[proto.UpdateWebsiteRequest]) (*connect.Response[proto.Website], error)
	DeleteWebsite(context.Context, *connect.Request[proto.DeleteWebsiteRequest]) (*connect.Response[proto.Empty], error)
	ListPasswords(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.PasswordList], error)
	SeedPasswords(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.SeedPasswordsResponse], error)
	UpdatePasswordComment(context.Context, *connect.Request[proto.UpdatePasswordCommentRequest]) (*connect.Response[proto.Empty], error)
	ClearPasswords(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.Empty], error)
	ListFiles(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.FileList], error)
	UpdateFile(context.Context, *connect.Request[proto.UpdateFileRequest]) (*connect.Response[proto.File], error)
	DeleteFile(context.Context, *connect.Request[proto.DeleteFileRequest]) (*connect.Response[proto.Empty], error)
	AddHostPort(context.Context, *connect.Request[proto.AddHostPortRequest]) (*connect.Response[proto.HostPort], error)
	DeleteHostPort(context.Context, *connect.Request[proto.DeleteHostPortRequest]) (*connect.Response[proto.Empty], error)
	UpdateHostPort(context.Context, *connect.Request[proto.UpdateHostPortRequest]) (*connect.Response[proto.HostPort], error)
	AddServicePort(context.Context, *connect.Request[proto.AddServicePortRequest]) (*connect.Response[proto.ServicePort], error)
	DeleteServicePort(context.Context, *connect.Request[proto.DeleteServicePortRequest]) (*connect.Response[proto.Empty], error)
	ImportHosts(context.Context, *connect.Request[proto.ImportHostsRequest]) (*connect.Response[proto.ImportHostsResponse], error)
	ClearHosts(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.Empty], error)
	AddServiceDependency(context.Context, *connect.Request[proto.AddServiceDependencyRequest]) (*connect.Response[proto.Empty], error)
	DeleteServiceDependency(context.Context, *connect.Request[proto.DeleteServiceDependencyRequest]) (*connect.Response[proto.Empty], error)
	ListNetworks(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.NetworkList], error)
	AddNetwork(context.Context, *connect.Request[proto.AddNetworkRequest]) (*connect.Response[proto.Network], error)
	UpdateNetwork(context.Context, *connect.Request[proto.UpdateNetworkRequest]) (*connect.Response[proto.Network], error)
	DeleteNetwork(context.Context, *connect.Request[proto.DeleteNetworkRequest]) (*connect.Response[proto.Empty], error)
	ListAllowedIPs(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.AllowedIPList], error)
	AddAllowedIP(context.Context, *connect.Request[proto.AddAllowedIPRequest]) (*connect.Response[proto.AllowedIP], error)
	UpdateAllowedIP(context.Context, *connect.Request[proto.UpdateAllowedIPRequest]) (*connect.Response[proto.AllowedIP], error)
	DeleteAllowedIP(context.Context, *connect.Request[proto.DeleteAllowedIPRequest]) (*connect.Response[proto.Empty], error)
}

// NewNorthstarClient constructs a client for the northstar.Northstar service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNorthstarClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NorthstarClient {
	baseURL = strings.TrimRight(baseURL, "/")
	northstarMethods := proto.File_northstar_proto.Services().ByName("Northstar").Methods()
	return &northstarClient{
		login: connect.NewClient[proto.LoginRequest, proto.LoginResponse](
			httpClient,
			baseURL+NorthstarLoginProcedure,
			connect.WithSchema(northstarMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		listHosts: connect.NewClient[proto.Empty, proto.HostList](
			httpClient,
			baseURL+NorthstarListHostsProcedure,
			connect.WithSchema(northstarMethods.ByName("ListHosts")),
			connect.WithClientOptions(opts...),
		),
		addHost: connect.NewClient[proto.AddHostRequest, proto.Host](
			httpClient,
			baseURL+NorthstarAddHostProcedure,
			connect.WithSchema(northstarMethods.ByName("AddHost")),
			connect.WithClientOptions(opts...),
		),
		updateHost: connect.NewClient[proto.UpdateHostRequest, proto.Host](
			httpClient,
			baseURL+NorthstarUpdateHostProcedure,
			connect.WithSchema(northstarMethods.ByName("UpdateHost")),
			connect.WithClientOptions(opts...),
		),
		deleteHost: connect.NewClient[proto.DeleteHostRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteHostProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteHost")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[proto.Empty, proto.ServiceList](
			httpClient,
			baseURL+NorthstarListServicesProcedure,
			connect.WithSchema(northstarMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		addService: connect.NewClient[proto.AddServiceRequest, proto.Service](
			httpClient,
			baseURL+NorthstarAddServiceProcedure,
			connect.WithSchema(northstarMethods.ByName("AddService")),
			connect.WithClientOptions(opts...),
		),
		updateService: connect.NewClient[proto.UpdateServiceRequest, proto.Service](
			httpClient,
			baseURL+NorthstarUpdateServiceProcedure,
			connect.WithSchema(northstarMethods.ByName("UpdateService")),
			connect.WithClientOptions(opts...),
		),
		deleteService: connect.NewClient[proto.DeleteServiceRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteServiceProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteService")),
			connect.WithClientOptions(opts...),
		),
		getCredentials: connect.NewClient[proto.CredentialRequest, proto.CredentialList](
			httpClient,
			baseURL+NorthstarGetCredentialsProcedure,
			connect.WithSchema(northstarMethods.ByName("GetCredentials")),
			connect.WithClientOptions(opts...),
		),
		listInjects: connect.NewClient[proto.Empty, proto.InjectList](
			httpClient,
			baseURL+NorthstarListInjectsProcedure,
			connect.WithSchema(northstarMethods.ByName("ListInjects")),
			connect.WithClientOptions(opts...),
		),
		addInject: connect.NewClient[proto.AddInjectRequest, proto.Inject](
			httpClient,
			baseURL+NorthstarAddInjectProcedure,
			connect.WithSchema(northstarMethods.ByName("AddInject")),
			connect.WithClientOptions(opts...),
		),
		updateInject: connect.NewClient[proto.UpdateInjectRequest, proto.Inject](
			httpClient,
			baseURL+NorthstarUpdateInjectProcedure,
			connect.WithSchema(northstarMethods.ByName("UpdateInject")),
			connect.WithClientOptions(opts...),
		),
		deleteInject: connect.NewClient[proto.DeleteInjectRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteInjectProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteInject")),
			connect.WithClientOptions(opts...),
		),
		listWebsites: connect.NewClient[proto.Empty, proto.WebsiteList](
			httpClient,
			baseURL+NorthstarListWebsitesProcedure,
			connect.WithSchema(northstarMethods.ByName("ListWebsites")),
			connect.WithClientOptions(opts...),
		),
		addWebsite: connect.NewClient[proto.AddWebsiteRequest, proto.Website](
			httpClient,
			baseURL+NorthstarAddWebsiteProcedure,
			connect.WithSchema(northstarMethods.ByName("AddWebsite")),
			connect.WithClientOptions(opts...),
		),
		updateWebsite: connect.NewClient[proto.UpdateWebsiteRequest, proto.Website](
			httpClient,
			baseURL+NorthstarUpdateWebsiteProcedure,
			connect.WithSchema(northstarMethods.ByName("UpdateWebsite")),
			connect.WithClientOptions(opts...),
		),
		deleteWebsite: connect.NewClient[proto.DeleteWebsiteRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteWebsiteProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteWebsite")),
			connect.WithClientOptions(opts...),
		),
		listPasswords: connect.NewClient[proto.Empty, proto.PasswordList](
			httpClient,
			baseURL+NorthstarListPasswordsProcedure,
			connect.WithSchema(northstarMethods.ByName("ListPasswords")),
			connect.WithClientOptions(opts...),
		),
		seedPasswords: connect.NewClient[proto.Empty, proto.SeedPasswordsResponse](
			httpClient,
			baseURL+NorthstarSeedPasswordsProcedure,
			connect.WithSchema(northstarMethods.ByName("SeedPasswords")),
			connect.WithClientOptions(opts...),
		),
		updatePasswordComment: connect.NewClient[proto.UpdatePasswordCommentRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarUpdatePasswordCommentProcedure,
			connect.WithSchema(northstarMethods.ByName("UpdatePasswordComment")),
			connect.WithClientOptions(opts...),
		),
		clearPasswords: connect.NewClient[proto.Empty, proto.Empty](
			httpClient,
			baseURL+NorthstarClearPasswordsProcedure,
			connect.WithSchema(northstarMethods.ByName("ClearPasswords")),
			connect.WithClientOptions(opts...),
		),
		listFiles: connect.NewClient[proto.Empty, proto.FileList](
			httpClient,
			baseURL+NorthstarListFilesProcedure,
			connect.WithSchema(northstarMethods.ByName("ListFiles")),
			connect.WithClientOptions(opts...),
		),
		updateFile: connect.NewClient[proto.UpdateFileRequest, proto.File](
			httpClient,
			baseURL+NorthstarUpdateFileProcedure,
			connect.WithSchema(northstarMethods.ByName("UpdateFile")),
			connect.WithClientOptions(opts...),
		),
		deleteFile: connect.NewClient[proto.DeleteFileRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteFileProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteFile")),
			connect.WithClientOptions(opts...),
		),
		addHostPort: connect.NewClient[proto.AddHostPortRequest, proto.HostPort](
			httpClient,
			baseURL+NorthstarAddHostPortProcedure,
			connect.WithSchema(northstarMethods.ByName("AddHostPort")),
			connect.WithClientOptions(opts...),
		),
		deleteHostPort: connect.NewClient[proto.DeleteHostPortRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteHostPortProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteHostPort")),
			connect.WithClientOptions(opts...),
		),
		updateHostPort: connect.NewClient[proto.UpdateHostPortRequest, proto.HostPort](
			httpClient,
			baseURL+NorthstarUpdateHostPortProcedure,
			connect.WithSchema(northstarMethods.ByName("UpdateHostPort")),
			connect.WithClientOptions(opts...),
		),
		addServicePort: connect.NewClient[proto.AddServicePortRequest, proto.ServicePort](
			httpClient,
			baseURL+NorthstarAddServicePortProcedure,
			connect.WithSchema(northstarMethods.ByName("AddServicePort")),
			connect.WithClientOptions(opts...),
		),
		deleteServicePort: connect.NewClient[proto.DeleteServicePortRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteServicePortProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteServicePort")),
			connect.WithClientOptions(opts...),
		),
		importHosts: connect.NewClient[proto.ImportHostsRequest, proto.ImportHostsResponse](
			httpClient,
			baseURL+NorthstarImportHostsProcedure,
			connect.WithSchema(northstarMethods.ByName("ImportHosts")),
			connect.WithClientOptions(opts...),
		),
		clearHosts: connect.NewClient[proto.Empty, proto.Empty](
			httpClient,
			baseURL+NorthstarClearHostsProcedure,
			connect.WithSchema(northstarMethods.ByName("ClearHosts")),
			connect.WithClientOptions(opts...),
		),
		addServiceDependency: connect.NewClient[proto.AddServiceDependencyRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarAddServiceDependencyProcedure,
			connect.WithSchema(northstarMethods.ByName("AddServiceDependency")),
			connect.WithClientOptions(opts...),
		),
		deleteServiceDependency: connect.NewClient[proto.DeleteServiceDependencyRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteServiceDependencyProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteServiceDependency")),
			connect.WithClientOptions(opts...),
		),
		listNetworks: connect.NewClient[proto.Empty, proto.NetworkList](
			httpClient,
			baseURL+NorthstarListNetworksProcedure,
			connect.WithSchema(northstarMethods.ByName("ListNetworks")),
			connect.WithClientOptions(opts...),
		),
		addNetwork: connect.NewClient[proto.AddNetworkRequest, proto.Network](
			httpClient,
			baseURL+NorthstarAddNetworkProcedure,
			connect.WithSchema(northstarMethods.ByName("AddNetwork")),
			connect.WithClientOptions(opts...),
		),
		updateNetwork: connect.NewClient[proto.UpdateNetworkRequest, proto.Network](
			httpClient,
			baseURL+NorthstarUpdateNetworkProcedure,
			connect.WithSchema(northstarMethods.ByName("UpdateNetwork")),
			connect.WithClientOptions(opts...),
		),
		deleteNetwork: connect.NewClient[proto.DeleteNetworkRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteNetworkProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteNetwork")),
			connect.WithClientOptions(opts...),
		),
		listAllowedIPs: connect.NewClient[proto.Empty, proto.AllowedIPList](
			httpClient,
			baseURL+NorthstarListAllowedIPsProcedure,
			connect.WithSchema(northstarMethods.ByName("ListAllowedIPs")),
			connect.WithClientOptions(opts...),
		),
		addAllowedIP: connect.NewClient[proto.AddAllowedIPRequest, proto.AllowedIP](
			httpClient,
			baseURL+NorthstarAddAllowedIPProcedure,
			connect.WithSchema(northstarMethods.ByName("AddAllowedIP")),
			connect.WithClientOptions(opts...),
		),
		updateAllowedIP: connect.NewClient[proto.UpdateAllowedIPRequest, proto.AllowedIP](
			httpClient,
			baseURL+NorthstarUpdateAllowedIPProcedure,
			connect.WithSchema(northstarMethods.ByName("UpdateAllowedIP")),
			connect.WithClientOptions(opts...),
		),
		deleteAllowedIP: connect.NewClient[proto.DeleteAllowedIPRequest, proto.Empty](
			httpClient,
			baseURL+NorthstarDeleteAllowedIPProcedure,
			connect.WithSchema(northstarMethods.ByName("DeleteAllowedIP")),
			connect.WithClientOptions(opts...),
		),
	}
}

// northstarClient implements NorthstarClient.
type northstarClient struct {
	login                   *connect.Client[proto.LoginRequest, proto.LoginResponse]
	listHosts               *connect.Client[proto.Empty, proto.HostList]
	addHost                 *connect.Client[proto.AddHostRequest, proto.Host]
	updateHost              *connect.Client[proto.UpdateHostRequest, proto.Host]
	deleteHost              *connect.Client[proto.DeleteHostRequest, proto.Empty]
	listServices            *connect.Client[proto.Empty, proto.ServiceList]
	addService              *connect.Client[proto.AddServiceRequest, proto.Service]
	updateService           *connect.Client[proto.UpdateServiceRequest, proto.Service]
	deleteService           *connect.Client[proto.DeleteServiceRequest, proto.Empty]
	getCredentials          *connect.Client[proto.CredentialRequest, proto.CredentialList]
	listInjects             *connect.Client[proto.Empty, proto.InjectList]
	addInject               *connect.Client[proto.AddInjectRequest, proto.Inject]
	updateInject            *connect.Client[proto.UpdateInjectRequest, proto.Inject]
	deleteInject            *connect.Client[proto.DeleteInjectRequest, proto.Empty]
	listWebsites            *connect.Client[proto.Empty, proto.WebsiteList]
	addWebsite              *connect.Client[proto.AddWebsiteRequest, proto.Website]
	updateWebsite           *connect.Client[proto.UpdateWebsiteRequest, proto.Website]
	deleteWebsite           *connect.Client[proto.DeleteWebsiteRequest, proto.Empty]
	listPasswords           *connect.Client[proto.Empty, proto.PasswordList]
	seedPasswords           *connect.Client[proto.Empty, proto.SeedPasswordsResponse]
	updatePasswordComment   *connect.Client[proto.UpdatePasswordCommentRequest, proto.Empty]
	clearPasswords          *connect.Client[proto.Empty, proto.Empty]
	listFiles               *connect.Client[proto.Empty, proto.FileList]
	updateFile              *connect.Client[proto.UpdateFileRequest, proto.File]
	deleteFile              *connect.Client[proto.DeleteFileRequest, proto.Empty]
	addHostPort             *connect.Client[proto.AddHostPortRequest, proto.HostPort]
	deleteHostPort          *connect.Client[proto.DeleteHostPortRequest, proto.Empty]
	updateHostPort          *connect.Client[proto.UpdateHostPortRequest, proto.HostPort]
	addServicePort          *connect.Client[proto.AddServicePortRequest, proto.ServicePort]
	deleteServicePort       *connect.Client[proto.DeleteServicePortRequest, proto.Empty]
	importHosts             *connect.Client[proto.ImportHostsRequest, proto.ImportHostsResponse]
	clearHosts              *connect.Client[proto.Empty, proto.Empty]
	addServiceDependency    *connect.Client[proto.AddServiceDependencyRequest, proto.Empty]
	deleteServiceDependency *connect.Client[proto.DeleteServiceDependencyRequest, proto.Empty]
	listNetworks            *connect.Client[proto.Empty, proto.NetworkList]
	addNetwork              *connect.Client[proto.AddNetworkRequest, proto.Network]
	updateNetwork           *connect.Client[proto.UpdateNetworkRequest, proto.Network]
	deleteNetwork           *connect.Client[proto.DeleteNetworkRequest, proto.Empty]
	listAllowedIPs          *connect.Client[proto.Empty, proto.AllowedIPList]
	addAllowedIP            *connect.Client[proto.AddAllowedIPRequest, proto.AllowedIP]
	updateAllowedIP         *connect.Client[proto.UpdateAllowedIPRequest, proto.AllowedIP]
	deleteAllowedIP         *connect.Client[proto.DeleteAllowedIPRequest, proto.Empty]
}

// Login calls northstar.Northstar.Login.
func (c *northstarClient) Login(ctx context.Context, req *connect.Request[proto.LoginRequest]) (*connect.Response[proto.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// ListHosts calls northstar.Northstar.ListHosts.
func (c *northstarClient) ListHosts(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.HostList], error) {
	return c.listHosts.CallUnary(ctx, req)
}

// AddHost calls northstar.Northstar.AddHost.
func (c *northstarClient) AddHost(ctx context.Context, req *connect.Request[proto.AddHostRequest]) (*connect.Response[proto.Host], error) {
	return c.addHost.CallUnary(ctx, req)
}

// UpdateHost calls northstar.Northstar.UpdateHost.
func (c *northstarClient) UpdateHost(ctx context.Context, req *connect.Request[proto.UpdateHostRequest]) (*connect.Response[proto.Host], error) {
	return c.updateHost.CallUnary(ctx, req)
}

// DeleteHost calls northstar.Northstar.DeleteHost.
func (c *northstarClient) DeleteHost(ctx context.Context, req *connect.Request[proto.DeleteHostRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteHost.CallUnary(ctx, req)
}

// ListServices calls northstar.Northstar.ListServices.
func (c *northstarClient) ListServices(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.ServiceList], error) {
	return c.listServices.CallUnary(ctx, req)
}

// AddService calls northstar.Northstar.AddService.
func (c *northstarClient) AddService(ctx context.Context, req *connect.Request[proto.AddServiceRequest]) (*connect.Response[proto.Service], error) {
	return c.addService.CallUnary(ctx, req)
}

// UpdateService calls northstar.Northstar.UpdateService.
func (c *northstarClient) UpdateService(ctx context.Context, req *connect.Request[proto.UpdateServiceRequest]) (*connect.Response[proto.Service], error) {
	return c.updateService.CallUnary(ctx, req)
}

// DeleteService calls northstar.Northstar.DeleteService.
func (c *northstarClient) DeleteService(ctx context.Context, req *connect.Request[proto.DeleteServiceRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteService.CallUnary(ctx, req)
}

// GetCredentials calls northstar.Northstar.GetCredentials.
func (c *northstarClient) GetCredentials(ctx context.Context, req *connect.Request[proto.CredentialRequest]) (*connect.Response[proto.CredentialList], error) {
	return c.getCredentials.CallUnary(ctx, req)
}

// ListInjects calls northstar.Northstar.ListInjects.
func (c *northstarClient) ListInjects(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.InjectList], error) {
	return c.listInjects.CallUnary(ctx, req)
}

// AddInject calls northstar.Northstar.AddInject.
func (c *northstarClient) AddInject(ctx context.Context, req *connect.Request[proto.AddInjectRequest]) (*connect.Response[proto.Inject], error) {
	return c.addInject.CallUnary(ctx, req)
}

// UpdateInject calls northstar.Northstar.UpdateInject.
func (c *northstarClient) UpdateInject(ctx context.Context, req *connect.Request[proto.UpdateInjectRequest]) (*connect.Response[proto.Inject], error) {
	return c.updateInject.CallUnary(ctx, req)
}

// DeleteInject calls northstar.Northstar.DeleteInject.
func (c *northstarClient) DeleteInject(ctx context.Context, req *connect.Request[proto.DeleteInjectRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteInject.CallUnary(ctx, req)
}

// ListWebsites calls northstar.Northstar.ListWebsites.
func (c *northstarClient) ListWebsites(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.WebsiteList], error) {
	return c.listWebsites.CallUnary(ctx, req)
}

// AddWebsite calls northstar.Northstar.AddWebsite.
func (c *northstarClient) AddWebsite(ctx context.Context, req *connect.Request[proto.AddWebsiteRequest]) (*connect.Response[proto.Website], error) {
	return c.addWebsite.CallUnary(ctx, req)
}

// UpdateWebsite calls northstar.Northstar.UpdateWebsite.
func (c *northstarClient) UpdateWebsite(ctx context.Context, req *connect.Request[proto.UpdateWebsiteRequest]) (*connect.Response[proto.Website], error) {
	return c.updateWebsite.CallUnary(ctx, req)
}

// DeleteWebsite calls northstar.Northstar.DeleteWebsite.
func (c *northstarClient) DeleteWebsite(ctx context.Context, req *connect.Request[proto.DeleteWebsiteRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteWebsite.CallUnary(ctx, req)
}

// ListPasswords calls northstar.Northstar.ListPasswords.
func (c *northstarClient) ListPasswords(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.PasswordList], error) {
	return c.listPasswords.CallUnary(ctx, req)
}

// SeedPasswords calls northstar.Northstar.SeedPasswords.
func (c *northstarClient) SeedPasswords(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.SeedPasswordsResponse], error) {
	return c.seedPasswords.CallUnary(ctx, req)
}

// UpdatePasswordComment calls northstar.Northstar.UpdatePasswordComment.
func (c *northstarClient) UpdatePasswordComment(ctx context.Context, req *connect.Request[proto.UpdatePasswordCommentRequest]) (*connect.Response[proto.Empty], error) {
	return c.updatePasswordComment.CallUnary(ctx, req)
}

// ClearPasswords calls northstar.Northstar.ClearPasswords.
func (c *northstarClient) ClearPasswords(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.Empty], error) {
	return c.clearPasswords.CallUnary(ctx, req)
}

// ListFiles calls northstar.Northstar.ListFiles.
func (c *northstarClient) ListFiles(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.FileList], error) {
	return c.listFiles.CallUnary(ctx, req)
}

// UpdateFile calls northstar.Northstar.UpdateFile.
func (c *northstarClient) UpdateFile(ctx context.Context, req *connect.Request[proto.UpdateFileRequest]) (*connect.Response[proto.File], error) {
	return c.updateFile.CallUnary(ctx, req)
}

// DeleteFile calls northstar.Northstar.DeleteFile.
func (c *northstarClient) DeleteFile(ctx context.Context, req *connect.Request[proto.DeleteFileRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteFile.CallUnary(ctx, req)
}

// AddHostPort calls northstar.Northstar.AddHostPort.
func (c *northstarClient) AddHostPort(ctx context.Context, req *connect.Request[proto.AddHostPortRequest]) (*connect.Response[proto.HostPort], error) {
	return c.addHostPort.CallUnary(ctx, req)
}

// DeleteHostPort calls northstar.Northstar.DeleteHostPort.
func (c *northstarClient) DeleteHostPort(ctx context.Context, req *connect.Request[proto.DeleteHostPortRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteHostPort.CallUnary(ctx, req)
}

// UpdateHostPort calls northstar.Northstar.UpdateHostPort.
func (c *northstarClient) UpdateHostPort(ctx context.Context, req *connect.Request[proto.UpdateHostPortRequest]) (*connect.Response[proto.HostPort], error) {
	return c.updateHostPort.CallUnary(ctx, req)
}

// AddServicePort calls northstar.Northstar.AddServicePort.
func (c *northstarClient) AddServicePort(ctx context.Context, req *connect.Request[proto.AddServicePortRequest]) (*connect.Response[proto.ServicePort], error) {
	return c.addServicePort.CallUnary(ctx, req)
}

// DeleteServicePort calls northstar.Northstar.DeleteServicePort.
func (c *northstarClient) DeleteServicePort(ctx context.Context, req *connect.Request[proto.DeleteServicePortRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteServicePort.CallUnary(ctx, req)
}

// ImportHosts calls northstar.Northstar.ImportHosts.
func (c *northstarClient) ImportHosts(ctx context.Context, req *connect.Request[proto.ImportHostsRequest]) (*connect.Response[proto.ImportHostsResponse], error) {
	return c.importHosts.CallUnary(ctx, req)
}

// ClearHosts calls northstar.Northstar.ClearHosts.
func (c *northstarClient) ClearHosts(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.Empty], error) {
	return c.clearHosts.CallUnary(ctx, req)
}

// AddServiceDependency calls northstar.Northstar.AddServiceDependency.
func (c *northstarClient) AddServiceDependency(ctx context.Context, req *connect.Request[proto.AddServiceDependencyRequest]) (*connect.Response[proto.Empty], error) {
	return c.addServiceDependency.CallUnary(ctx, req)
}

// DeleteServiceDependency calls northstar.Northstar.DeleteServiceDependency.
func (c *northstarClient) DeleteServiceDependency(ctx context.Context, req *connect.Request[proto.DeleteServiceDependencyRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteServiceDependency.CallUnary(ctx, req)
}

// ListNetworks calls northstar.Northstar.ListNetworks.
func (c *northstarClient) ListNetworks(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.NetworkList], error) {
	return c.listNetworks.CallUnary(ctx, req)
}

// AddNetwork calls northstar.Northstar.AddNetwork.
func (c *northstarClient) AddNetwork(ctx context.Context, req *connect.Request[proto.AddNetworkRequest]) (*connect.Response[proto.Network], error) {
	return c.addNetwork.CallUnary(ctx, req)
}

// UpdateNetwork calls northstar.Northstar.UpdateNetwork.
func (c *northstarClient) UpdateNetwork(ctx context.Context, req *connect.Request[proto.UpdateNetworkRequest]) (*connect.Response[proto.Network], error) {
	return c.updateNetwork.CallUnary(ctx, req)
}

// DeleteNetwork calls northstar.Northstar.DeleteNetwork.
func (c *northstarClient) DeleteNetwork(ctx context.Context, req *connect.Request[proto.DeleteNetworkRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteNetwork.CallUnary(ctx, req)
}

// ListAllowedIPs calls northstar.Northstar.ListAllowedIPs.
func (c *northstarClient) ListAllowedIPs(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.AllowedIPList], error) {
	return c.listAllowedIPs.CallUnary(ctx, req)
}

// AddAllowedIP calls northstar.Northstar.AddAllowedIP.
func (c *northstarClient) AddAllowedIP(ctx context.Context, req *connect.Request[proto.AddAllowedIPRequest]) (*connect.Response[proto.AllowedIP], error) {
	return c.addAllowedIP.CallUnary(ctx, req)
}

// UpdateAllowedIP calls northstar.Northstar.UpdateAllowedIP.
func (c *northstarClient) UpdateAllowedIP(ctx context.Context, req *connect.Request[proto.UpdateAllowedIPRequest]) (*connect.Response[proto.AllowedIP], error) {
	return c.updateAllowedIP.CallUnary(ctx, req)
}

// DeleteAllowedIP calls northstar.Northstar.DeleteAllowedIP.
func (c *northstarClient) DeleteAllowedIP(ctx context.Context, req *connect.Request[proto.DeleteAllowedIPRequest]) (*connect.Response[proto.Empty], error) {
	return c.deleteAllowedIP.CallUnary(ctx, req)
}

// NorthstarHandler is an implementation of the northstar.Northstar service.
type NorthstarHandler interface {
	Login(context.Context, *connect.Request[proto.LoginRequest]) (*connect.Response[proto.LoginResponse], error)
	ListHosts(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.HostList], error)
	AddHost(context.Context, *connect.Request[proto.AddHostRequest]) (*connect.Response[proto.Host], error)
	UpdateHost(context.Context, *connect.Request[proto.UpdateHostRequest]) (*connect.Response[proto.Host], error)
	DeleteHost(context.Context, *connect.Request[proto.DeleteHostRequest]) (*connect.Response[proto.Empty], error)
	ListServices(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.ServiceList], error)
	AddService(context.Context, *connect.Request[proto.AddServiceRequest]) (*connect.Response[proto.Service], error)
	UpdateService(context.Context, *connect.Request[proto.UpdateServiceRequest]) (*connect.Response[proto.Service], error)
	DeleteService(context.Context, *connect.Request[proto.DeleteServiceRequest]) (*connect.Response[proto.Empty], error)
	GetCredentials(context.Context, *connect.Request[proto.CredentialRequest]) (*connect.Response[proto.CredentialList], error)
	ListInjects(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.InjectList], error)
	AddInject(context.Context, *connect.Request[proto.AddInjectRequest]) (*connect.Response[proto.Inject], error)
	UpdateInject(context.Context, *connect.Request[proto.UpdateInjectRequest]) (*connect.Response[proto.Inject], error)
	DeleteInject(context.Context, *connect.Request[proto.DeleteInjectRequest]) (*connect.Response[proto.Empty], error)
	ListWebsites(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.WebsiteList], error)
	AddWebsite(context.Context, *connect.Request[proto.AddWebsiteRequest]) (*connect.Response[proto.Website], error)
	UpdateWebsite(context.Context, *connect.Request[proto.UpdateWebsiteRequest]) (*connect.Response[proto.Website], error)
	DeleteWebsite(context.Context, *connect.Request[proto.DeleteWebsiteRequest]) (*connect.Response[proto.Empty], error)
	ListPasswords(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.PasswordList], error)
	SeedPasswords(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.SeedPasswordsResponse], error)
	UpdatePasswordComment(context.Context, *connect.Request[proto.UpdatePasswordCommentRequest]) (*connect.Response[proto.Empty], error)
	ClearPasswords(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.Empty], error)
	ListFiles(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.FileList], error)
	UpdateFile(context.Context, *connect.Request[proto.UpdateFileRequest]) (*connect.Response[proto.File], error)
	DeleteFile(context.Context, *connect.Request[proto.DeleteFileRequest]) (*connect.Response[proto.Empty], error)
	AddHostPort(context.Context, *connect.Request[proto.AddHostPortRequest]) (*connect.Response[proto.HostPort], error)
	DeleteHostPort(context.Context, *connect.Request[proto.DeleteHostPortRequest]) (*connect.Response[proto.Empty], error)
	UpdateHostPort(context.Context, *connect.Request[proto.UpdateHostPortRequest]) (*connect.Response[proto.HostPort], error)
	AddServicePort(context.Context, *connect.Request[proto.AddServicePortRequest]) (*connect.Response[proto.ServicePort], error)
	DeleteServicePort(context.Context, *connect.Request[proto.DeleteServicePortRequest]) (*connect.Response[proto.Empty], error)
	ImportHosts(context.Context, *connect.Request[proto.ImportHostsRequest]) (*connect.Response[proto.ImportHostsResponse], error)
	ClearHosts(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.Empty], error)
	AddServiceDependency(context.Context, *connect.Request[proto.AddServiceDependencyRequest]) (*connect.Response[proto.Empty], error)
	DeleteServiceDependency(context.Context, *connect.Request[proto.DeleteServiceDependencyRequest]) (*connect.Response[proto.Empty], error)
	ListNetworks(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.NetworkList], error)
	AddNetwork(context.Context, *connect.Request[proto.AddNetworkRequest]) (*connect.Response[proto.Network], error)
	UpdateNetwork(context.Context, *connect.Request[proto.UpdateNetworkRequest]) (*connect.Response[proto.Network], error)
	DeleteNetwork(context.Context, *connect.Request[proto.DeleteNetworkRequest]) (*connect.Response[proto.Empty], error)
	ListAllowedIPs(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.AllowedIPList], error)
	AddAllowedIP(context.Context, *connect.Request[proto.AddAllowedIPRequest]) (*connect.Response[proto.AllowedIP], error)
	UpdateAllowedIP(context.Context, *connect.Request[proto.UpdateAllowedIPRequest]) (*connect.Response[proto.AllowedIP], error)
	DeleteAllowedIP(context.Context, *connect.Request[proto.DeleteAllowedIPRequest]) (*connect.Response[proto.Empty], error)
}

// NewNorthstarHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNorthstarHandler(svc NorthstarHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	northstarMethods := proto.File_northstar_proto.Services().ByName("Northstar").Methods()
	northstarLoginHandler := connect.NewUnaryHandler(
		NorthstarLoginProcedure,
		svc.Login,
		connect.WithSchema(northstarMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	northstarListHostsHandler := connect.NewUnaryHandler(
		NorthstarListHostsProcedure,
		svc.ListHosts,
		connect.WithSchema(northstarMethods.ByName("ListHosts")),
		connect.WithHandlerOptions(opts...),
	)
	northstarAddHostHandler := connect.NewUnaryHandler(
		NorthstarAddHostProcedure,
		svc.AddHost,
		connect.WithSchema(northstarMethods.ByName("AddHost")),
		connect.WithHandlerOptions(opts...),
	)
	northstarUpdateHostHandler := connect.NewUnaryHandler(
		NorthstarUpdateHostProcedure,
		svc.UpdateHost,
		connect.WithSchema(northstarMethods.ByName("UpdateHost")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteHostHandler := connect.NewUnaryHandler(
		NorthstarDeleteHostProcedure,
		svc.DeleteHost,
		connect.WithSchema(northstarMethods.ByName("DeleteHost")),
		connect.WithHandlerOptions(opts...),
	)
	northstarListServicesHandler := connect.NewUnaryHandler(
		NorthstarListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(northstarMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	northstarAddServiceHandler := connect.NewUnaryHandler(
		NorthstarAddServiceProcedure,
		svc.AddService,
		connect.WithSchema(northstarMethods.ByName("AddService")),
		connect.WithHandlerOptions(opts...),
	)
	northstarUpdateServiceHandler := connect.NewUnaryHandler(
		NorthstarUpdateServiceProcedure,
		svc.UpdateService,
		connect.WithSchema(northstarMethods.ByName("UpdateService")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteServiceHandler := connect.NewUnaryHandler(
		NorthstarDeleteServiceProcedure,
		svc.DeleteService,
		connect.WithSchema(northstarMethods.ByName("DeleteService")),
		connect.WithHandlerOptions(opts...),
	)
	northstarGetCredentialsHandler := connect.NewUnaryHandler(
		NorthstarGetCredentialsProcedure,
		svc.GetCredentials,
		connect.WithSchema(northstarMethods.ByName("GetCredentials")),
		connect.WithHandlerOptions(opts...),
	)
	northstarListInjectsHandler := connect.NewUnaryHandler(
		NorthstarListInjectsProcedure,
		svc.ListInjects,
		connect.WithSchema(northstarMethods.ByName("ListInjects")),
		connect.WithHandlerOptions(opts...),
	)
	northstarAddInjectHandler := connect.NewUnaryHandler(
		NorthstarAddInjectProcedure,
		svc.AddInject,
		connect.WithSchema(northstarMethods.ByName("AddInject")),
		connect.WithHandlerOptions(opts...),
	)
	northstarUpdateInjectHandler := connect.NewUnaryHandler(
		NorthstarUpdateInjectProcedure,
		svc.UpdateInject,
		connect.WithSchema(northstarMethods.ByName("UpdateInject")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteInjectHandler := connect.NewUnaryHandler(
		NorthstarDeleteInjectProcedure,
		svc.DeleteInject,
		connect.WithSchema(northstarMethods.ByName("DeleteInject")),
		connect.WithHandlerOptions(opts...),
	)
	northstarListWebsitesHandler := connect.NewUnaryHandler(
		NorthstarListWebsitesProcedure,
		svc.ListWebsites,
		connect.WithSchema(northstarMethods.ByName("ListWebsites")),
		connect.WithHandlerOptions(opts...),
	)
	northstarAddWebsiteHandler := connect.NewUnaryHandler(
		NorthstarAddWebsiteProcedure,
		svc.AddWebsite,
		connect.WithSchema(northstarMethods.ByName("AddWebsite")),
		connect.WithHandlerOptions(opts...),
	)
	northstarUpdateWebsiteHandler := connect.NewUnaryHandler(
		NorthstarUpdateWebsiteProcedure,
		svc.UpdateWebsite,
		connect.WithSchema(northstarMethods.ByName("UpdateWebsite")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteWebsiteHandler := connect.NewUnaryHandler(
		NorthstarDeleteWebsiteProcedure,
		svc.DeleteWebsite,
		connect.WithSchema(northstarMethods.ByName("DeleteWebsite")),
		connect.WithHandlerOptions(opts...),
	)
	northstarListPasswordsHandler := connect.NewUnaryHandler(
		NorthstarListPasswordsProcedure,
		svc.ListPasswords,
		connect.WithSchema(northstarMethods.ByName("ListPasswords")),
		connect.WithHandlerOptions(opts...),
	)
	northstarSeedPasswordsHandler := connect.NewUnaryHandler(
		NorthstarSeedPasswordsProcedure,
		svc.SeedPasswords,
		connect.WithSchema(northstarMethods.ByName("SeedPasswords")),
		connect.WithHandlerOptions(opts...),
	)
	northstarUpdatePasswordCommentHandler := connect.NewUnaryHandler(
		NorthstarUpdatePasswordCommentProcedure,
		svc.UpdatePasswordComment,
		connect.WithSchema(northstarMethods.ByName("UpdatePasswordComment")),
		connect.WithHandlerOptions(opts...),
	)
	northstarClearPasswordsHandler := connect.NewUnaryHandler(
		NorthstarClearPasswordsProcedure,
		svc.ClearPasswords,
		connect.WithSchema(northstarMethods.ByName("ClearPasswords")),
		connect.WithHandlerOptions(opts...),
	)
	northstarListFilesHandler := connect.NewUnaryHandler(
		NorthstarListFilesProcedure,
		svc.ListFiles,
		connect.WithSchema(northstarMethods.ByName("ListFiles")),
		connect.WithHandlerOptions(opts...),
	)
	northstarUpdateFileHandler := connect.NewUnaryHandler(
		NorthstarUpdateFileProcedure,
		svc.UpdateFile,
		connect.WithSchema(northstarMethods.ByName("UpdateFile")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteFileHandler := connect.NewUnaryHandler(
		NorthstarDeleteFileProcedure,
		svc.DeleteFile,
		connect.WithSchema(northstarMethods.ByName("DeleteFile")),
		connect.WithHandlerOptions(opts...),
	)
	northstarAddHostPortHandler := connect.NewUnaryHandler(
		NorthstarAddHostPortProcedure,
		svc.AddHostPort,
		connect.WithSchema(northstarMethods.ByName("AddHostPort")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteHostPortHandler := connect.NewUnaryHandler(
		NorthstarDeleteHostPortProcedure,
		svc.DeleteHostPort,
		connect.WithSchema(northstarMethods.ByName("DeleteHostPort")),
		connect.WithHandlerOptions(opts...),
	)
	northstarUpdateHostPortHandler := connect.NewUnaryHandler(
		NorthstarUpdateHostPortProcedure,
		svc.UpdateHostPort,
		connect.WithSchema(northstarMethods.ByName("UpdateHostPort")),
		connect.WithHandlerOptions(opts...),
	)
	northstarAddServicePortHandler := connect.NewUnaryHandler(
		NorthstarAddServicePortProcedure,
		svc.AddServicePort,
		connect.WithSchema(northstarMethods.ByName("AddServicePort")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteServicePortHandler := connect.NewUnaryHandler(
		NorthstarDeleteServicePortProcedure,
		svc.DeleteServicePort,
		connect.WithSchema(northstarMethods.ByName("DeleteServicePort")),
		connect.WithHandlerOptions(opts...),
	)
	northstarImportHostsHandler := connect.NewUnaryHandler(
		NorthstarImportHostsProcedure,
		svc.ImportHosts,
		connect.WithSchema(northstarMethods.ByName("ImportHosts")),
		connect.WithHandlerOptions(opts...),
	)
	northstarClearHostsHandler := connect.NewUnaryHandler(
		NorthstarClearHostsProcedure,
		svc.ClearHosts,
		connect.WithSchema(northstarMethods.ByName("ClearHosts")),
		connect.WithHandlerOptions(opts...),
	)
	northstarAddServiceDependencyHandler := connect.NewUnaryHandler(
		NorthstarAddServiceDependencyProcedure,
		svc.AddServiceDependency,
		connect.WithSchema(northstarMethods.ByName("AddServiceDependency")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteServiceDependencyHandler := connect.NewUnaryHandler(
		NorthstarDeleteServiceDependencyProcedure,
		svc.DeleteServiceDependency,
		connect.WithSchema(northstarMethods.ByName("DeleteServiceDependency")),
		connect.WithHandlerOptions(opts...),
	)
	northstarListNetworksHandler := connect.NewUnaryHandler(
		NorthstarListNetworksProcedure,
		svc.ListNetworks,
		connect.WithSchema(northstarMethods.ByName("ListNetworks")),
		connect.WithHandlerOptions(opts...),
	)
	northstarAddNetworkHandler := connect.NewUnaryHandler(
		NorthstarAddNetworkProcedure,
		svc.AddNetwork,
		connect.WithSchema(northstarMethods.ByName("AddNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	northstarUpdateNetworkHandler := connect.NewUnaryHandler(
		NorthstarUpdateNetworkProcedure,
		svc.UpdateNetwork,
		connect.WithSchema(northstarMethods.ByName("UpdateNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteNetworkHandler := connect.NewUnaryHandler(
		NorthstarDeleteNetworkProcedure,
		svc.DeleteNetwork,
		connect.WithSchema(northstarMethods.ByName("DeleteNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	northstarListAllowedIPsHandler := connect.NewUnaryHandler(
		NorthstarListAllowedIPsProcedure,
		svc.ListAllowedIPs,
		connect.WithSchema(northstarMethods.ByName("ListAllowedIPs")),
		connect.WithHandlerOptions(opts...),
	)
	northstarAddAllowedIPHandler := connect.NewUnaryHandler(
		NorthstarAddAllowedIPProcedure,
		svc.AddAllowedIP,
		connect.WithSchema(northstarMethods.ByName("AddAllowedIP")),
		connect.WithHandlerOptions(opts...),
	)
	northstarUpdateAllowedIPHandler := connect.NewUnaryHandler(
		NorthstarUpdateAllowedIPProcedure,
		svc.UpdateAllowedIP,
		connect.WithSchema(northstarMethods.ByName("UpdateAllowedIP")),
		connect.WithHandlerOptions(opts...),
	)
	northstarDeleteAllowedIPHandler := connect.NewUnaryHandler(
		NorthstarDeleteAllowedIPProcedure,
		svc.DeleteAllowedIP,
		connect.WithSchema(northstarMethods.ByName("DeleteAllowedIP")),
		connect.WithHandlerOptions(opts...),
	)
	return "/northstar.Northstar/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NorthstarLoginProcedure:
			northstarLoginHandler.ServeHTTP(w, r)
		case NorthstarListHostsProcedure:
			northstarListHostsHandler.ServeHTTP(w, r)
		case NorthstarAddHostProcedure:
			northstarAddHostHandler.ServeHTTP(w, r)
		case NorthstarUpdateHostProcedure:
			northstarUpdateHostHandler.ServeHTTP(w, r)
		case NorthstarDeleteHostProcedure:
			northstarDeleteHostHandler.ServeHTTP(w, r)
		case NorthstarListServicesProcedure:
			northstarListServicesHandler.ServeHTTP(w, r)
		case NorthstarAddServiceProcedure:
			northstarAddServiceHandler.ServeHTTP(w, r)
		case NorthstarUpdateServiceProcedure:
			northstarUpdateServiceHandler.ServeHTTP(w, r)
		case NorthstarDeleteServiceProcedure:
			northstarDeleteServiceHandler.ServeHTTP(w, r)
		case NorthstarGetCredentialsProcedure:
			northstarGetCredentialsHandler.ServeHTTP(w, r)
		case NorthstarListInjectsProcedure:
			northstarListInjectsHandler.ServeHTTP(w, r)
		case NorthstarAddInjectProcedure:
			northstarAddInjectHandler.ServeHTTP(w, r)
		case NorthstarUpdateInjectProcedure:
			northstarUpdateInjectHandler.ServeHTTP(w, r)
		case NorthstarDeleteInjectProcedure:
			northstarDeleteInjectHandler.ServeHTTP(w, r)
		case NorthstarListWebsitesProcedure:
			northstarListWebsitesHandler.ServeHTTP(w, r)
		case NorthstarAddWebsiteProcedure:
			northstarAddWebsiteHandler.ServeHTTP(w, r)
		case NorthstarUpdateWebsiteProcedure:
			northstarUpdateWebsiteHandler.ServeHTTP(w, r)
		case NorthstarDeleteWebsiteProcedure:
			northstarDeleteWebsiteHandler.ServeHTTP(w, r)
		case NorthstarListPasswordsProcedure:
			northstarListPasswordsHandler.ServeHTTP(w, r)
		case NorthstarSeedPasswordsProcedure:
			northstarSeedPasswordsHandler.ServeHTTP(w, r)
		case NorthstarUpdatePasswordCommentProcedure:
			northstarUpdatePasswordCommentHandler.ServeHTTP(w, r)
		case NorthstarClearPasswordsProcedure:
			northstarClearPasswordsHandler.ServeHTTP(w, r)
		case NorthstarListFilesProcedure:
			northstarListFilesHandler.ServeHTTP(w, r)
		case NorthstarUpdateFileProcedure:
			northstarUpdateFileHandler.ServeHTTP(w, r)
		case NorthstarDeleteFileProcedure:
			northstarDeleteFileHandler.ServeHTTP(w, r)
		case NorthstarAddHostPortProcedure:
			northstarAddHostPortHandler.ServeHTTP(w, r)
		case NorthstarDeleteHostPortProcedure:
			northstarDeleteHostPortHandler.ServeHTTP(w, r)
		case NorthstarUpdateHostPortProcedure:
			northstarUpdateHostPortHandler.ServeHTTP(w, r)
		case NorthstarAddServicePortProcedure:
			northstarAddServicePortHandler.ServeHTTP(w, r)
		case NorthstarDeleteServicePortProcedure:
			northstarDeleteServicePortHandler.ServeHTTP(w, r)
		case NorthstarImportHostsProcedure:
			northstarImportHostsHandler.ServeHTTP(w, r)
		case NorthstarClearHostsProcedure:
			northstarClearHostsHandler.ServeHTTP(w, r)
		case NorthstarAddServiceDependencyProcedure:
			northstarAddServiceDependencyHandler.ServeHTTP(w, r)
		case NorthstarDeleteServiceDependencyProcedure:
			northstarDeleteServiceDependencyHandler.ServeHTTP(w, r)
		case NorthstarListNetworksProcedure:
			northstarListNetworksHandler.ServeHTTP(w, r)
		case NorthstarAddNetworkProcedure:
			northstarAddNetworkHandler.ServeHTTP(w, r)
		case NorthstarUpdateNetworkProcedure:
			northstarUpdateNetworkHandler.ServeHTTP(w, r)
		case NorthstarDeleteNetworkProcedure:
			northstarDeleteNetworkHandler.ServeHTTP(w, r)
		case NorthstarListAllowedIPsProcedure:
			northstarListAllowedIPsHandler.ServeHTTP(w, r)
		case NorthstarAddAllowedIPProcedure:
			northstarAddAllowedIPHandler.ServeHTTP(w, r)
		case NorthstarUpdateAllowedIPProcedure:
			northstarUpdateAllowedIPHandler.ServeHTTP(w, r)
		case NorthstarDeleteAllowedIPProcedure:
			northstarDeleteAllowedIPHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNorthstarHandler returns CodeUnimplemented from all methods.
type UnimplementedNorthstarHandler struct{}

func (UnimplementedNorthstarHandler) Login(context.Context, *connect.Request[proto.LoginRequest]) (*connect.Response[proto.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.Login is not implemented"))
}

func (UnimplementedNorthstarHandler) ListHosts(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.HostList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ListHosts is not implemented"))
}

func (UnimplementedNorthstarHandler) AddHost(context.Context, *connect.Request[proto.AddHostRequest]) (*connect.Response[proto.Host], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.AddHost is not implemented"))
}

func (UnimplementedNorthstarHandler) UpdateHost(context.Context, *connect.Request[proto.UpdateHostRequest]) (*connect.Response[proto.Host], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.UpdateHost is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteHost(context.Context, *connect.Request[proto.DeleteHostRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteHost is not implemented"))
}

func (UnimplementedNorthstarHandler) ListServices(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.ServiceList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ListServices is not implemented"))
}

func (UnimplementedNorthstarHandler) AddService(context.Context, *connect.Request[proto.AddServiceRequest]) (*connect.Response[proto.Service], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.AddService is not implemented"))
}

func (UnimplementedNorthstarHandler) UpdateService(context.Context, *connect.Request[proto.UpdateServiceRequest]) (*connect.Response[proto.Service], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.UpdateService is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteService(context.Context, *connect.Request[proto.DeleteServiceRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteService is not implemented"))
}

func (UnimplementedNorthstarHandler) GetCredentials(context.Context, *connect.Request[proto.CredentialRequest]) (*connect.Response[proto.CredentialList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.GetCredentials is not implemented"))
}

func (UnimplementedNorthstarHandler) ListInjects(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.InjectList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ListInjects is not implemented"))
}

func (UnimplementedNorthstarHandler) AddInject(context.Context, *connect.Request[proto.AddInjectRequest]) (*connect.Response[proto.Inject], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.AddInject is not implemented"))
}

func (UnimplementedNorthstarHandler) UpdateInject(context.Context, *connect.Request[proto.UpdateInjectRequest]) (*connect.Response[proto.Inject], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.UpdateInject is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteInject(context.Context, *connect.Request[proto.DeleteInjectRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteInject is not implemented"))
}

func (UnimplementedNorthstarHandler) ListWebsites(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.WebsiteList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ListWebsites is not implemented"))
}

func (UnimplementedNorthstarHandler) AddWebsite(context.Context, *connect.Request[proto.AddWebsiteRequest]) (*connect.Response[proto.Website], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.AddWebsite is not implemented"))
}

func (UnimplementedNorthstarHandler) UpdateWebsite(context.Context, *connect.Request[proto.UpdateWebsiteRequest]) (*connect.Response[proto.Website], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.UpdateWebsite is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteWebsite(context.Context, *connect.Request[proto.DeleteWebsiteRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteWebsite is not implemented"))
}

func (UnimplementedNorthstarHandler) ListPasswords(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.PasswordList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ListPasswords is not implemented"))
}

func (UnimplementedNorthstarHandler) SeedPasswords(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.SeedPasswordsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.SeedPasswords is not implemented"))
}

func (UnimplementedNorthstarHandler) UpdatePasswordComment(context.Context, *connect.Request[proto.UpdatePasswordCommentRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.UpdatePasswordComment is not implemented"))
}

func (UnimplementedNorthstarHandler) ClearPasswords(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ClearPasswords is not implemented"))
}

func (UnimplementedNorthstarHandler) ListFiles(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.FileList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ListFiles is not implemented"))
}

func (UnimplementedNorthstarHandler) UpdateFile(context.Context, *connect.Request[proto.UpdateFileRequest]) (*connect.Response[proto.File], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.UpdateFile is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteFile(context.Context, *connect.Request[proto.DeleteFileRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteFile is not implemented"))
}

func (UnimplementedNorthstarHandler) AddHostPort(context.Context, *connect.Request[proto.AddHostPortRequest]) (*connect.Response[proto.HostPort], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.AddHostPort is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteHostPort(context.Context, *connect.Request[proto.DeleteHostPortRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteHostPort is not implemented"))
}

func (UnimplementedNorthstarHandler) UpdateHostPort(context.Context, *connect.Request[proto.UpdateHostPortRequest]) (*connect.Response[proto.HostPort], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.UpdateHostPort is not implemented"))
}

func (UnimplementedNorthstarHandler) AddServicePort(context.Context, *connect.Request[proto.AddServicePortRequest]) (*connect.Response[proto.ServicePort], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.AddServicePort is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteServicePort(context.Context, *connect.Request[proto.DeleteServicePortRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteServicePort is not implemented"))
}

func (UnimplementedNorthstarHandler) ImportHosts(context.Context, *connect.Request[proto.ImportHostsRequest]) (*connect.Response[proto.ImportHostsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ImportHosts is not implemented"))
}

func (UnimplementedNorthstarHandler) ClearHosts(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ClearHosts is not implemented"))
}

func (UnimplementedNorthstarHandler) AddServiceDependency(context.Context, *connect.Request[proto.AddServiceDependencyRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.AddServiceDependency is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteServiceDependency(context.Context, *connect.Request[proto.DeleteServiceDependencyRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteServiceDependency is not implemented"))
}

func (UnimplementedNorthstarHandler) ListNetworks(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.NetworkList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ListNetworks is not implemented"))
}

func (UnimplementedNorthstarHandler) AddNetwork(context.Context, *connect.Request[proto.AddNetworkRequest]) (*connect.Response[proto.Network], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.AddNetwork is not implemented"))
}

func (UnimplementedNorthstarHandler) UpdateNetwork(context.Context, *connect.Request[proto.UpdateNetworkRequest]) (*connect.Response[proto.Network], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.UpdateNetwork is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteNetwork(context.Context, *connect.Request[proto.DeleteNetworkRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteNetwork is not implemented"))
}

func (UnimplementedNorthstarHandler) ListAllowedIPs(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.AllowedIPList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.ListAllowedIPs is not implemented"))
}

func (UnimplementedNorthstarHandler) AddAllowedIP(context.Context, *connect.Request[proto.AddAllowedIPRequest]) (*connect.Response[proto.AllowedIP], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.AddAllowedIP is not implemented"))
}

func (UnimplementedNorthstarHandler) UpdateAllowedIP(context.Context, *connect.Request[proto.UpdateAllowedIPRequest]) (*connect.Response[proto.AllowedIP], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.UpdateAllowedIP is not implemented"))
}

func (UnimplementedNorthstarHandler) DeleteAllowedIP(context.Context, *connect.Request[proto.DeleteAllowedIPRequest]) (*connect.Response[proto.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("northstar.Northstar.DeleteAllowedIP is not implemented"))
}
